name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Download dependencies
        run: go mod download
      
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w" -o cascade-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/cascade
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cascade-${{ matrix.goos }}-${{ matrix.goarch }}
          path: cascade-${{ matrix.goos }}-${{ matrix.goarch }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Prepare release
        run: |
          mkdir -p release
          cp artifacts/cascade-linux-amd64/cascade-linux-amd64 release/
          cp artifacts/cascade-linux-arm64/cascade-linux-arm64 release/
          cd release
          sha256sum cascade-linux-* | tee SHA256SUMS
          chmod +x cascade-linux-*
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true

